# Specify how to handle Cloud Build Logging.  Dummy update!
options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: $PROJECT_ID
# Build the Docker container image.
steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - build
  - us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genai:$COMMIT_SHA
  - --builder
  - gcr.io/buildpacks/builder:latest
  - --network
  - cloudbuild
  # Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genai:$COMMIT_SHA']
  # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'genai'
    - '--image'
    - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genai:$COMMIT_SHA'
    - '--region'
    - 'us-west1'
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genai:$COMMIT_SHA'
