steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/gerson-henriquez/testRepository.git']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy', '--appyaml=app.yaml']


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy', 'cron.yaml']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
  pool: 
    name: projects/gersonh-pf-dev/locations/us-central1/workerPools/my-private-pool